#
# Inspired by Jekyll's page:
# https://jekyllrb.com/docs/continuous-integration/travis-ci/
#

os: linux
language: ruby
rvm:
  - 2.4.1

before_script:
 - chmod +x ./script/cibuild

# assume bundler is being used, therefore the `install` step will run `bundle install` by default
script: ./script/cibuild

# branch whitelist -- master branch holds our sources
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

# caching bundler gem packages will speed up build
cache: bundler

# Disable email notifications about the outcome of your builds
notifications:
  email: false
