# Site wide configuration

title:            mod_cluster
locale:           en_US
url:              https://www.modcluster.io

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
#highlighter: pygments
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - github-pages

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false
  input: GFM

# Site owner
owner:
  name: mod_cluster
  avatar: mod_cluster-200x200.png
  bio: "mod_cluster is an intelligent native Apache httpd-based and pure-Java Undertow-based load-balancer"
  email: mod_cluster-dev@lists.jboss.org
  jira: MODCLUSTER
  irc: "https://webchat.freenode.net/?channels=%23mod_cluster&uio=MT1mYWxzZSYxNj10cnVlJjk9dHJ1ZSYxMT0yMzY35"
  user-forum: "https://developer.jboss.org/en/mod_cluster"
  mailing-list: "https://lists.jboss.org/mailman/listinfo/mod_cluster-dev"
  dockerhub: "https://hub.docker.com/r/karm/mod_cluster-master-dockerhub/"
  downloads: "https://github.com/modcluster/mod_cluster/releases"
  documentation: "https://docs.modcluster.io"
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: modcluster
  stackoverflow: #123456/username   from a "https://stackoverflow.com/users/12345678910/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]

# https://jekyllrb.com/docs/continuous-integration/travis-ci/
exclude: ["vendor", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
